const $=s=>document.querySelector(s);
const DEFAULT_BACKEND='https://eara-pwa.jesuscruz1984.workers.dev';
const MEMKEY='earaMemoryV2';
const PERSONAKEY='earaPersona';
const VOICEKEY='earaVoice';
let stream=null,screenStream=null,lastReply='',lastSpeech='',cameraEnabled=true,micEnabled=true,screenSharing=false;
const personalities={helpful:'Helpful Assistant',concise:'Fast & Concise',expert:'Expert Analyst',companion:'Friendly Companion',fieldtech:'Field Technician',observer:'Curious Observer'};
const premiumVoices={asteria:'Asteria',luna:'Luna',athena:'Athena',stella:'Stella',angus:'Angus',orion:'Orion',perseus:'Perseus',zeus:'Zeus',helios:'Helios',hera:'Hera',arcas:'Arcas',orpheus:'Orpheus'};
const staleCapability=/\b(i(?:'m| am) (?:a )?large language model|i (?:do not|don't|cannot|can't) (?:see|hear|reply|respond|converse)|one-way communication|text-based inputs only|cannot visually|don't have the capability to visually|not capable of engaging in a conversation)\b/i;
function backend(){return DEFAULT_BACKEND}
function badge(x){$('#badge').textContent='● '+x}
function memory(){try{return JSON.parse(localStorage.getItem(MEMKEY)||'[]')}catch(_){return []}}
function saveMemory(arr){localStorage.setItem(MEMKEY,JSON.stringify(arr.slice(-500)));renderMemory()}
function addMemory(entry){const arr=memory();arr.push({...entry,ts:new Date().toISOString()});saveMemory(arr)}
function words(s){return new Set(String(s||'').toLowerCase().match(/[a-z0-9]{3,}/g)||[])}
function memoryContext(query){const q=words(query),arr=memory().filter(m=>!staleCapability.test(String(m.assistant||'')));const scored=arr.map((m,i)=>{let score=i/Math.max(1,arr.length)*2;const hay=words((m.user||'')+' '+(m.assistant||''));q.forEach(w=>{if(hay.has(w))score+=4});return {m,score}}).sort((a,b)=>b.score-a.score).slice(0,8).map(x=>x.m).reverse();return scored.map(m=>`[${new Date(m.ts).toLocaleString()}] User: ${String(m.user||'').slice(0,260)}\nEARA: ${String(m.assistant||'').slice(0,520)}${m.vision?'\n[Vision frame processed]':''}`).join('\n\n')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function linkify(s){return esc(s).replace(/(https?:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noopener">$1</a>').replace(/\n/g,'<br>')}
function setReply(text){lastReply=String(text||'');$('#reply').innerHTML=linkify(lastReply);$('#copyReply').disabled=!lastReply;$('#speak').disabled=!lastReply}
function renderMemory(){const arr=memory();$('#memoryCount').textContent=`${arr.length} saved interactions`;const box=$('#memoryList');if(!arr.length){box.innerHTML='<div class="small">No memories yet. EARA will retain every question and AI response on this device.</div>';return}box.innerHTML=arr.slice().reverse().map(m=>`<article class="mem"><div class="small">${new Date(m.ts).toLocaleString()} · ${esc(personalities[m.persona]||m.persona||'EARA')}${m.vision?' · Vision':''}${m.source==='screen'?' · Screen':''}</div><b>You:</b> <span>${linkify(m.user)}</span><br><b>EARA:</b> <span>${linkify(m.assistant)}</span></article>`).join('')}
async function chooseWideCamera(){try{const devices=await navigator.mediaDevices.enumerateDevices();const cams=devices.filter(d=>d.kind==='videoinput');const wide=cams.find(d=>/ultra\s*wide|0\.5|wide angle|back.*wide/i.test(d.label));if(!wide)return false;const vt=stream?.getVideoTracks?.()[0];if(vt)vt.stop();const vs=await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:wide.deviceId},width:{ideal:1280},height:{ideal:720}},audio:false});const newTrack=vs.getVideoTracks()[0];stream.addTrack(newTrack);if(!screenSharing){video.srcObject=stream;await video.play()}return true}catch(_){return false}}
async function applyMinZoom(){try{const t=stream?.getVideoTracks?.()[0],cap=t?.getCapabilities?.();if(cap?.zoom){await t.applyConstraints({advanced:[{zoom:cap.zoom.min}]})}}catch(_){}}
async function startMedia(silent=false){if(stream)return true;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:true});if(!screenSharing){video.srcObject=stream;await video.play()}await chooseWideCamera();await applyMinZoom();cameraEnabled=true;micEnabled=true;$('#cam').textContent=screenSharing?'SCREEN VISION':'WIDE VISION';$('#cameraBtn').textContent='Disable Camera';$('#micBtn').textContent='Disable Mic';$('#permissionBtn').classList.add('hidden');$('#mediaControls').classList.remove('hidden');badge(screenSharing?'Screen Live':'Live');$('#state').textContent=screenSharing?'Screen sharing — say “Hey Robot”':'Listening — say “Hey Robot”';window.dispatchEvent(new CustomEvent('eara-media-ready'));return true}catch(e){if(!silent){$('#permissionBtn').classList.remove('hidden');$('#state').textContent='Tap Enable Camera + Mic once to grant permission.'}return false}}
function stopCamera(){if(!stream)return;cameraEnabled=!cameraEnabled;stream.getVideoTracks().forEach(t=>t.enabled=cameraEnabled);$('#cameraBtn').textContent=cameraEnabled?'Disable Camera':'Enable Camera';if(!screenSharing)$('#cam').textContent=cameraEnabled?'WIDE VISION':'CAMERA PAUSED'}
function stopMic(){if(!stream)return;micEnabled=!micEnabled;stream.getAudioTracks().forEach(t=>t.enabled=micEnabled);$('#micBtn').textContent=micEnabled?'Disable Mic':'Enable Mic';if(micEnabled)window.dispatchEvent(new CustomEvent('eara-mic-enabled'));else window.dispatchEvent(new CustomEvent('eara-mic-disabled'));$('#state').textContent=micEnabled?(screenSharing?'Screen sharing — say “Hey Robot”':'Listening — say “Hey Robot”'):'Microphone disabled'}
function screenShareSupported(){return !!navigator.mediaDevices?.getDisplayMedia}
async function startScreenShare(){if(screenSharing)return true;if(!screenShareSupported()){const msg='Live screen sharing is not supported by iPhone Safari/PWA. EARA screen share works on supported desktop browsers; iPhone requires a native EARA app.';$('#state').textContent=msg;badge('Screen Share Unavailable');setReply(msg);lastSpeech='iPhone requires the native EARA app for live screen sharing.';if(window.say)window.say(lastSpeech);return false}try{const ds=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const track=ds.getVideoTracks()[0];if(!track)throw new Error('No screen video track returned');screenStream=ds;screenSharing=true;video.srcObject=screenStream;await video.play();$('#screenBtn').textContent='Stop Screen Share';$('#cam').textContent='SCREEN VISION';$('#state').textContent='Screen sharing — say “Hey Robot”';badge('Screen Live');track.addEventListener('ended',()=>stopScreenShare(),{once:true});return true}catch(e){if(e?.name==='NotAllowedError'){$('#state').textContent='Screen sharing was canceled or blocked.';badge('Live');return false}$('#state').textContent='Screen share error: '+(e?.message||e);badge('Screen Error');return false}}
async function stopScreenShare(){if(screenStream){screenStream.getTracks().forEach(t=>{try{t.stop()}catch(_){}});screenStream=null}screenSharing=false;$('#screenBtn').textContent='Share Screen';if(stream){video.srcObject=stream;try{await video.play()}catch(_){}}$('#cam').textContent=cameraEnabled?'WIDE VISION':'CAMERA PAUSED';$('#state').textContent=micEnabled?'Listening — say “Hey Robot”':'Microphone disabled';badge('Live')}
function shouldUseVision(q){if(screenSharing)return true;if(!cameraEnabled)return false;return /\b(see|look|looking|camera|show(?:ing)?|this|that|these|those|holding|in front|what(?:'s| is) (?:this|that|here)|identify|recognize|read (?:this|it)|scan|label|model number|serial|picture|image|photo|object|item|bottle|device|what am i|what do i)\b/i.test(String(q||''))}
function snap(){const c=$('#canvas'),vw=video.videoWidth||960,vh=video.videoHeight||540;if(!screenSharing&&(!stream||!cameraEnabled))return null;const maxW=960,scale=Math.min(1,maxW/vw);c.width=Math.max(1,Math.round(vw*scale));c.height=Math.max(1,Math.round(vh*scale));c.getContext('2d').drawImage(video,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.62)}
function fail(e){const msg=String(e?.message||e);if(/10,000 neurons|daily free allocation|4006/i.test(msg)){setReply('Cloudflare AI free allowance is used up for today. Tavily web search can still work for non-camera searches, and the allowance resets daily.');$('#state').textContent='Daily AI allowance used';badge('AI Limit');$('#ai').textContent='AI limit';return}setReply('Connection error: '+msg);$('#state').textContent='Error';badge('Error');$('#ai').textContent='Error'}
async function askAI(text){const q=String(text||'').trim();if(!q)return;try{$('#state').textContent='Thinking…';badge('Thinking');const useVision=shouldUseVision(q);const image=useVision?snap():null;const persona=localStorage.getItem(PERSONAKEY)||'helpful';const mem=memoryContext(q);const r=await fetch(backend()+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:q,image,memory:mem,personality:persona,visionActive:!!image,source:screenSharing?'screen':'camera'})});const raw=await r.text();if(!r.ok)throw new Error('HTTP '+r.status+': '+raw);const j=JSON.parse(raw),answer=j.text||'No reply';lastSpeech=String(j.speech||answer);setReply(answer);addMemory({user:q,assistant:answer,vision:!!image,persona,source:image?(screenSharing?'screen':'camera'):'none'});$('#transcript').textContent='You: '+q;$('#ai').textContent=j.webUsed?'WEB + AI':(screenSharing&&image?'SCREEN + AI':(image?'VISION + AI':(j.modelMode==='deep'?'DEEP AI':'AUTO SMART')));badge(screenSharing?'Screen Live':'Live');if(window.say)window.say(lastSpeech);return answer}catch(e){fail(e);throw e}}
async function copyText(t){try{await navigator.clipboard.writeText(t);badge('Copied');setTimeout(()=>badge(screenSharing?'Screen Live':'Live'),900)}catch(_){}}
function setPersona(v){localStorage.setItem(PERSONAKEY,v);if($('#persona'))$('#persona').value=v;if($('#personaLiveSelect'))$('#personaLiveSelect').value=v;$('#personaLive').textContent=personalities[v]||v}
function normalizeVoice(v){const s=String(v||'');return s.startsWith('local:')||s.startsWith('premium:')?s:'local:default'}
function setVoice(v){const safe=normalizeVoice(v);localStorage.setItem(VOICEKEY,safe);if($('#voiceLiveSelect'))$('#voiceLiveSelect').value=safe;if($('#voiceCoreSelect'))$('#voiceCoreSelect').value=safe;window.dispatchEvent(new CustomEvent('eara-voice-changed',{detail:{voice:safe}}))}
function addVoiceBaseOptions(sel){if(!sel)return;sel.innerHTML='';const free=document.createElement('optgroup');free.label='FREE — iPhone / device voices';const def=document.createElement('option');def.value='local:default';def.textContent='iPhone Default — FREE';free.appendChild(def);sel.appendChild(free);const prem=document.createElement('optgroup');prem.label='PREMIUM — uses Cloudflare AI';Object.entries(premiumVoices).forEach(([k,n])=>{const o=document.createElement('option');o.value='premium:'+k;o.textContent=n+' — Premium';prem.appendChild(o)});sel.appendChild(prem)}
function populateDeviceVoices(){const all=(window.speechSynthesis?.getVoices?.()||[]).filter(v=>/^en(?:-|_)/i.test(v.lang||''));['#voiceLiveSelect','#voiceCoreSelect'].forEach(id=>{const sel=$(id);if(!sel)return;const current=normalizeVoice(localStorage.getItem(VOICEKEY));addVoiceBaseOptions(sel);const free=sel.querySelector('optgroup');all.slice(0,18).forEach(v=>{const o=document.createElement('option');o.value='local:'+v.voiceURI;o.textContent=v.name+' — FREE';free.appendChild(o)});sel.value=[...sel.options].some(o=>o.value===current)?current:'local:default'});if(!localStorage.getItem(VOICEKEY)||!normalizeVoice(localStorage.getItem(VOICEKEY)).startsWith('local:')&&!normalizeVoice(localStorage.getItem(VOICEKEY)).startsWith('premium:'))setVoice('local:default')}
function makeVoiceSelect(id){const sel=document.createElement('select');sel.id=id;sel.style.width='100%';addVoiceBaseOptions(sel);sel.onchange=e=>setVoice(e.target.value);return sel}
$('#permissionBtn').onclick=()=>startMedia(false);
$('#cameraBtn').onclick=stopCamera;$('#micBtn').onclick=stopMic;$('#screenBtn').onclick=()=>screenSharing?stopScreenShare():startScreenShare();
$('#ask').onclick=()=>{const t=$('#typed').value.trim();if(t){$('#typed').value='';askAI(t)}};
$('#typed').addEventListener('keydown',e=>{if(e.key==='Enter')$('#ask').click()});
$('#speak').onclick=()=>window.say?.(lastSpeech||lastReply);$('#copyReply').onclick=()=>copyText(lastReply);
$('#copyMemory').onclick=()=>copyText(memory().map(m=>`[${new Date(m.ts).toLocaleString()}]\nYou: ${m.user}\nEARA: ${m.assistant}${m.vision?'\nVision frame processed':''}${m.source==='screen'?'\nSource: shared screen':''}`).join('\n\n'));
$('#clearMemory').onclick=()=>{if(confirm('Clear all EARA memory saved on this device?'))saveMemory([])};
if($('#persona'))$('#persona').onchange=e=>setPersona(e.target.value);
const controls=$('#mediaControls');if(controls){const wrap=document.createElement('div');wrap.style.marginTop='10px';wrap.innerHTML='<div class="small" style="margin-bottom:6px">Agent personality</div><select id="personaLiveSelect" style="width:100%"><option value="helpful">Helpful Assistant</option><option value="concise">Fast & Concise</option><option value="expert">Expert Analyst</option><option value="companion">Friendly Companion</option><option value="fieldtech">Field Technician</option><option value="observer">Curious Observer</option></select><div class="small" style="margin:10px 0 6px">Voice</div>';wrap.appendChild(makeVoiceSelect('voiceLiveSelect'));const note=document.createElement('div');note.className='small';note.style.marginTop='8px';note.textContent='AUTO SMART: GLM-4.7-Flash for normal conversation, GPT-OSS 120B only for hard questions, Tavily for live web, vision only when you ask about what EARA sees.';wrap.appendChild(note);controls.insertAdjacentElement('afterend',wrap);$('#personaLiveSelect').onchange=e=>setPersona(e.target.value)}
const core=$('#settings .pad');if(core){const d=document.createElement('div');d.innerHTML='<div class="small" style="margin:12px 0 6px">Voice</div>';d.appendChild(makeVoiceSelect('voiceCoreSelect'));const n=document.createElement('div');n.className='small';n.style.marginTop='8px';n.textContent='FREE voices use your iPhone/device speech engine and use zero Cloudflare Neurons. Premium voices use Deepgram Aura through Cloudflare.';d.appendChild(n);core.appendChild(d)}
const initialPersona=localStorage.getItem(PERSONAKEY)||'helpful';setPersona(initialPersona);const oldVoice=localStorage.getItem(VOICEKEY);if(!oldVoice||(!oldVoice.startsWith('local:')&&!oldVoice.startsWith('premium:')))localStorage.setItem(VOICEKEY,'local:default');populateDeviceVoices();if(window.speechSynthesis){window.speechSynthesis.onvoiceschanged=populateDeviceVoices}setVoice(localStorage.getItem(VOICEKEY)||'local:default');renderMemory();
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');['live','memory','tasks','settings'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==b.dataset.tab));if(b.dataset.tab==='memory')renderMemory()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
window.askAI=askAI;window.startMedia=startMedia;window.getEaraStream=()=>stream;window.isEaraMicEnabled=()=>micEnabled;window.getEaraVoice=()=>normalizeVoice(localStorage.getItem(VOICEKEY)||'local:default');window.isEaraScreenSharing=()=>screenSharing;
setTimeout(()=>startMedia(true).then(ok=>{if(!ok){$('#permissionBtn').classList.remove('hidden');$('#state').textContent='Tap Enable Camera + Mic once.'}}),350);